language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm i -g yarn
  - yarn global add -g @angular/cli
  - yarn
script:
- cd front
- ng update
- ng lint
- ng build --prod
script:
- cd front
- ng lint
- ng build
notifications:
 slack: dinuti:3LUFGSdQUxe6Qxv9JiXLpuB9
