language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli@7.3.9
  - npm i -g tslint
script:
- cd front
- ng lint
- ng build --prod
script:
- cd front
- ng lint
- ng build
notifications:
 slack: dinuti:3LUFGSdQUxe6Qxv9JiXLpuB9
