language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm i -g @angular/cli
script:
  - cd front
  - npm i
  - ng build --prod
  - ng lint
notifications:
 slack: dinuti:3LUFGSdQUxe6Qxv9JiXLpuB9
