language: node_js
node_js:
  - "10.11.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm i @angular-devkit/build-angular
script:
- cd front
- ng lint
- ng build --prod