language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm i -g @angular/cli
  - npm i -g newman
script:
  - cd front
  - npm i
  - ng build --prod
  - ng lint
  - cd ../back
  - npm i
  - npm run lint
  - npm run build
  - cd ..
  - newman run postman/dinuti.postman_collection.json -e postman/dinuti.postman_environment.json
notifications:
 slack: dinuti:3LUFGSdQUxe6Qxv9JiXLpuB9
