version: '3.5'
services:
  front-service:
    container_name: front-container
    build: 
      context: ./front
      args:
        env: prod
    ports:
      - '8080:80'
  back-service:
    container_name: back-container
    restart: always
    build: ./back
    ports:
      - '5000:5000'
    depends_on:
      - mongo-service
  mongo-service:
    container_name: mongo-container
    image: mongo
    # volumes:
    #   - ./back/dinuti:/data/db/